= judo-meta-query

image::https://github.com/BlackBeltTechnology/judo-meta-query/actions/workflows/build.yml/badge.svg?branch=develop[link="https://github.com/BlackBeltTechnology/judo-meta-query/actions/workflows/build.yml" float="center"]

== Introduction

This repository contains the Query meta model.

It acts as an eclipse plugin with features and sites, can be used standalone and in standard OSGi (without eclipse).

This is not an SQL model, but a model representing transformation logic for Expression-based queries. The output of this
is used later for RDBMS query generation.

== Context

This project is a building block of the https://github.com/BlackBeltTechnology/judo-community[judo-community] aggregator
project. In order to better understand how this module fits into our ecosystem, please check the corresponding documentation!

== Contributing to the project

Everyone is welcome to contribute to JUDO! As a starter, please read the corresponding link:CONTRIBUTING.adoc[CONTRIBUTING] guide for details!

== License

This project is licensed under the https://www.eclipse.org/legal/epl-2.0/[Eclipse Public License - v 2.0].

== Query meta model

* node: abstract
    ** gettype: entity
    ** not all of its relations can be used everywhere

* select: concrete select for an entity
    ** from: the entity to be selected
    ** each TO has 1 relevant select

* subselects: query
    ** transferrelation: reason why the subselect is needed
    ** used to navigate on relations
    ** embedded select: workaround to be able to contain a select if not available from TO-s
    ** base: where to start navigation

* subselectfeature: e.g.: select ... from ... where (select...) > 10

* Targets: projection, after querying data, in which form we need the date, result to be placed in

* join
    ** base: to what it is joined (recursively queries partners)

* referenced join: (single reference? maybe?)
    ** reference: entity relation 

* feature: something that the select or join wil returned
    ** target mapping: the attribute type of the result from feature

* featurewithnode:
    ** features that has strong relation to entities
    ** <|-- Attribute: entity attribute
    ** <|-- idAttribute: entity id
    ** <|-- TypeAttribute: entity type, version, create time etc.

* Constant: e.g.: 5 in a derived, trivial

* Entitytypename:
    ** used with inheritance

* Variable:
    ** category and name + type -> e.g.: String!getVariable(..., ...)

* Function: e.g.: LIKE(...) in a select
    ** parametername, parmetervalue -> used to be able to map expression to query

* filter: filters used within WHERE

== Joe notes

. Subselect in runtime is query
